import gymnasium as gym
import time
import json
import numpy as np
from IPython.utils.wildcard import is_type
from PyQt6.QtWidgets import QApplication
from IQ_Dataset import IQ_Dataset # used for real data
import rfrl_gym.renderers
import rfrl_gym.detectors
import rfrl_gym.entities
import scipy.signal as signal
from ..pywaspgen.burst_def import BurstDef
from ..pywaspgen.iq_datagen import IQDatagen


class RFRLGymIQEnv3(gym.Env):
    """
    Reinforcement learning environment for Radio Frequency (RF) scenarios using Gymnasium,
    utilizing IQ RF and PyWaspgen for in-phase and quadrature (IQ) data generation.
    
    This class loads scenario configurations from a specified JSON file and a PyWaspgen 
    configuration file to initialize the environment's channels, entities, signal detectors, 
    IQ data generation parameters, and action/observation spaces.
    
    Parameters
    ----------
    scenario_filename : str
        The filename of the JSON scenario configuration file. This file must be located 
        in the 'scenarios/' directory relative to the execution path.
    pywasp_config : str
        The filepath to the JSON configuration file used for PyWaspgen IQ data generation.
    num_episodes : int, optional
        The number of episodes to run in the environment. Default is 1.
    
    Attributes
    ----------
    num_episodes : int
        Number of episodes for the environment run.
    scenario_metadata : dict
        The raw parsed JSON dictionary containing all scenario configurations.
    samples_per_step : int
        The number of IQ samples generated per step, derived from `pywasp_config`.
    seed : int
        The random seed used for generation, derived from `pywasp_config`.
    num_channels : int
        Number of available RF channels in the environment.
    max_steps : int
        The maximum number of steps allowed per episode.
    observation_mode : {'detect', 'classify'}
        The type of observations returned to the agent.
    reward_mode : {'dsa', 'jam'}
        The reward structure used for the agent.
    target_entity : str
        The dictionary key/label of the target entity from the scenario file.
    detector : object
        The detector object instantiated from `rfrl_gym.detectors.DetectorGenerator`.
    t : numpy.ndarray
        Linear space array representing time over the samples per step.
    fc : numpy.ndarray
        Linear space array representing the center frequencies of the channels.
    sos : numpy.ndarray
        Second-order sections representation of the Butterworth filter used for signal processing.
    entity_generator : rfrl_gym.entities.EntityGenerator
        The generator object used to create the entities in the environment.
    entity_list : list
        A list of initialized entity objects generated by the `entity_generator`.
    num_entities : int
        The total number of entities instantiated in the environment.
    target_idx : int
        The internal numerical index assigned to the target entity.
    render_mode : {'null', 'terminal', 'pyqt'}
        The method used for rendering the environment.
    render_fps : int
        Frames per second to use when rendering the environment.
    next_frame_time : int
        Internal tracker for rendering timing.
    pyqt_app : PyQt5.QtWidgets.QApplication
        The PyQt application instance, initialized only if `render_mode` is 'pyqt'.
    action_space : gym.spaces.Discrete
        The discrete action space, sized `1 + num_channels`.
    observation_base : int
        The base value used to calculate the observation space size (2 for 'detect', 
        `1 + num_entities` for 'classify').
    observation_space : gym.spaces.Discrete
        The discrete observation space, sized `observation_base ** num_channels`.
    pywaspgen_iq_gen : IQDatagen
        The PyWaspgen instance used to generate the base IQ data.
    user_burst_list : list of list of BurstDef
        Nested list containing PyWaspgen burst definitions (`BurstDef`) for each entity 
        based on their modem parameters and channel assignments.
    rng : numpy.random.Generator
        The numpy random number generator instance initialized with `seed`.
    current_channel : int
        Internal counter used to track the current channel assignment during burst initialization.
    
    Notes
    -----
    The `scenario_filename` parameter points to a JSON file that must contain 
    'environment', 'entities', and 'render' configuration blocks. 
    
    The `pywasp_config` parameter points to a JSON file that must contain 'spectrum' 
    (with 'observation_duration') and 'generation' (with 'rand_seed') blocks to 
    properly configure the IQ data generation.
    """
    
    metadata = {'render_modes': ['null', 'terminal', 'pyqt'], 'render_fps': 4,
                'reward_modes': ['dsa', 'jam'],
                'observation_modes': ['detect', 'classify']}

    def __init__(self, scenario_filename,
                 pywasp_config,
                 num_episodes=1):
        self.num_episodes = num_episodes
        # Load in the JSON scenario file and check for valid entries.
        f_idx = open('scenarios/' + scenario_filename)
        self.scenario_metadata = json.load(f_idx)
        self.__validate_scenario_metadata()
        # load in the config file and determine IQ samples per step
        instance = json.load(open(pywasp_config))
        self.samples_per_step = instance['spectrum']['observation_duration']
        self.seed = instance['generation']['rand_seed']  # todo adjust seed away from pywasp generation
        # set global seed for environment init
        np.random.seed(self.seed)
        # Get the environment parameters from the scenario file.
        self.num_channels = self.scenario_metadata['environment']['num_channels']
        self.max_steps = self.scenario_metadata['environment']['max_steps']
        self.observation_mode = self.scenario_metadata['environment']['observation_mode']
        self.reward_mode = self.scenario_metadata['environment']['reward_mode']
        self.target_entity = self.scenario_metadata['environment']['target_entity']
        # generate the IQ_Dataset
        self.data_path = [self.scenario_metadata['environment']['data_path']]
        self.iq_ds = IQ_Dataset(self.data_path, window=self.samples_per_step)





        detector_gen = rfrl_gym.detectors.DetectorGenerator(self.scenario_metadata)
        self.detector = detector_gen.detector_out()
        self.t = np.linspace(0, self.samples_per_step, self.samples_per_step)
        channel_width = 1.0 / self.num_channels  #  channel width for fc
        # Create array of channel centers
        self.fc = np.linspace(-0.5 + channel_width / 2, 0.5 - channel_width / 2, self.num_channels)
        self.sos = signal.butter(100, 1 / self.num_channels, output='sos')

        # Get the entity parameters from the scenario file and initialize the entities.
        self.entity_generator = rfrl_gym.entities.EntityGenerator(self.scenario_metadata)

        self.entity_list = self.entity_generator.get_entity_list()
        self.num_entities = len(self.entity_list)
        # Method below is consistent with __get_entity_actions_and_observation which creates action_history
        entity_idx = 0
        for entity in self.scenario_metadata['entities']:
            entity_idx += 1
            if entity == self.target_entity:
                self.target_idx = entity_idx

        # Get the render parameters from the scenario file and initialize the render if necessary.
        self.render_mode = self.scenario_metadata['render']['render_mode']
        self.render_fps = self.scenario_metadata['render']['render_fps']
        self.next_frame_time = 0

        if self.render_mode == 'pyqt':
            self.pyqt_app = QApplication([])

        # Set the gym's baseline action and observation spaces.
        self.action_space = gym.spaces.Discrete(self.num_channels)
        # low and high are only for random sampling, using arbitrary values
        self.observation_space = gym.spaces.Box(low=-100, high=100,
                                                shape=(2,self.samples_per_step), dtype=np.float64)

        # data generation
        self.signal_generator = IQDatagen(pywasp_config)
        self.user_burst_list = []
        self.rng = np.random.default_rng(self.seed)

        # load the entity information from the json file and create the Pywasgen bursts
        for entity in self.entity_list:
            if "order" not in entity.modem_params.keys():
                entity.modem_params["order"] = None

    def _get_entity_actions(self):
        action_history_step = {}
        for entity in self.entity_list:
            entity_action = entity.get_action(self.info)
            action_history_step[entity.entity_label] = entity_action
        return action_history_step

    def _get_true_step_occupancy(self):
        "must be run after action_history has been updated for step"
        true_history_step = np.zeros(self.num_channels)
        for key, value in self.info['action_history'].items():
            if value[self.info['step_number']] != -1 and key != 'user_agent':
                true_history_step[value[self.info['step_number']]] = 1  # if channel is occupied flag it
        return true_history_step.astype(np.int8)

    def agent_iq(self, action):
        """
        method to generate the agent BurstDef on step -- can be overloaded to accomadate different action spaces
        Args:
            action: agent action passed in on step
        Returns: agent BurstDef
        """
        center_frequency = self.fc[action] + (self.rng.uniform(low=0, high=self.num_channels) / self.num_channels)

    def iq_gen(self):
        """
        update burst list on step with entity and agent actions
        Returns: signal_data, action_history_step

        """
        burst_list = []
        action_history_step = self._get_entity_actions()

        for entity in self.entity_list:
            action = action_history_step[entity.entity_label]
            if action != -1:  # entity is on -- (-1 is off)
                center_frequency = self.rng.uniform(entity.modem_params['center_frequency'][0],
                                                    entity.modem_params['center_frequency'][1])
                new_center_frequency = self.fc[action] + center_frequency / self.num_channels
                burst_list.append(BurstDef(
                    cent_freq=new_center_frequency,
                    bandwidth=(entity.modem_params["bandwidth"] / self.num_channels),
                    start=int(entity.modem_params["start"] * self.samples_per_step),
                    duration=int(entity.modem_params["duration"] * self.samples_per_step),
                    sig_type={
                        "label": str(str(entity.modem_params["order"]) + str(entity.modem_params["type"])),
                        "type": entity.modem_params["type"],
                        "order": entity.modem_params["order"]},
                ))
            else:  # entity is in off position
                pass

        signal_data, self.user_burst_list = self.signal_generator.gen_iqdata([burst_list])
        ## add in the recorded data to the IQ on each step
        #print(signal_data[0][:10], signal_data[0].shape)
        recorded_step_data = self.iq_ds.__getitem__(self.info['step_number'])[0]
        #print(recorded_step_data[:10], recorded_step_data.shape)
        signal_data[0] += recorded_step_data.numpy()
        #print(signal_data[0][:10], signal_data[0].shape)
        return signal_data, action_history_step

    def step(self, action):
        #action -= 1
        self.info['step_number'] += 1
        self.info['action_history']["user_agent"][self.info['step_number']] = action
        # call gen iq to get signal data and entity ground truth
        signal_data, action_history_step = self.iq_gen()
        for key, value in action_history_step.items():
            self.info['action_history'][key][self.info['step_number']] = value
        self.info['true_history'][self.info['step_number']] = self._get_true_step_occupancy()
        self.info['spectrum_data'] = np.roll(self.info['spectrum_data'], self.samples_per_step, axis=0)
        #self.info['spectrum_data'][0:self.samples_per_step] += signal_data[0]
        self.info['spectrum_data'][0:self.samples_per_step] = signal_data[0]
        # Update return variables and run the render.
        done = False
        if self.info['step_number'] == self.max_steps:
            self.info['episode_reward'] = np.append(self.info['episode_reward'],
                                                    self.info['cumulative_reward'][self.info['step_number']])
            done = True
        # outputs the IQ data for the observation, and dummy variable 0 for reward on base
        return self.__observation_space_encoder(None), 0, done, done, self.info

    def reset(self, options=None, seed=None):
        # Temporarily store episode specific variables if they exist.
        if hasattr(self, 'info') and isinstance(options, type(None)):
            episode_number = self.info['episode_number']
            episode_reward = self.info['episode_reward']
        else:
            episode_number = -1
            episode_reward = np.array([], dtype=float)
            if self.render_mode == 'terminal':
                self.renderer = rfrl_gym.renderers.terminal_renderer.TerminalRenderer(self.num_episodes,
                                                                                      self.scenario_metadata)
            if self.render_mode == 'pyqt':
                self.renderer = rfrl_gym.renderers.pyqt_renderer.PyQtRenderer(self.num_episodes,
                                                                              self.scenario_metadata,
                                                                              'iq',
                                                                              self.samples_per_step)
            if self.render_mode != 'null':
                self.renderer.reset()
        # print('starting info')
        # Reset the gym info dictionary and if necessary restore episode variables.
        self.info = {}
        self.info['step_number'] = 0
        self.info['num_entities'] = self.num_entities
        self.info['num_episodes'] = self.num_episodes
        self.info['episode_reward'] = episode_reward
        self.info['episode_number'] = episode_number + 1
        # todo consider way to make dynamic if we have multiple agents in scene
        self.info['action_history'] = {"user_agent": -1 + np.zeros(self.max_steps + 1, dtype=int)}
        for entity in self.entity_list:
            self.info['action_history'][entity.entity_label] = -1 + np.zeros(self.max_steps + 1, dtype=int)
        self.info['true_history'] = np.zeros((self.max_steps + 1, self.num_channels), dtype=int)
        self.info['observation_history'] = np.zeros((self.max_steps + 1, self.num_channels), dtype=int)
        self.info['reward_history'] = np.zeros(self.max_steps + 1, dtype=float)
        self.info['cumulative_reward'] = np.zeros(self.max_steps + 1, dtype=float)
        self.info['sensing_history'] = np.zeros((self.max_steps + 1, self.num_channels), dtype=int)
        self.info['sensing_energy_history'] = np.zeros((self.max_steps + 1, self.num_channels), dtype=float)

        for entity in self.entity_list:
            entity.reset(self.info)

        signal_data, action_history_step = self.iq_gen()
        for key, value in action_history_step.items():
            self.info['action_history'][key][self.info['step_number']] = value
        self.info['true_history'][self.info['step_number']] = self._get_true_step_occupancy()
        # Instantiate the spectrum of samples and then use Pywaspgen to generate the initial bursts
        # This is mostly to create the size needed to work with PyQt Renderer
        self.info['spectrum_data'] = np.random.normal(0.0, np.sqrt(0.5), self.samples_per_step * \
                                                      self.scenario_metadata['render']['render_history']) + 1.0j * \
                                     (np.random.normal(0.0, np.sqrt(0.5), self.samples_per_step * \
                                                       self.scenario_metadata['render']['render_history']))
        # add signals to noise
        self.info['spectrum_data'][0:self.samples_per_step] += signal_data[0]
        return self.observation_space.sample(), {}

    def render(self):
        if self.render_mode != 'null':
            if self.info['step_number'] == 0:
                self.next_frame_time = time.time()

            self.renderer.render(self.info)
            self.next_frame_time += 1.0 / self.render_fps
            time.sleep(1 / self.render_fps)

            if time.time() < self.next_frame_time:
                time.sleep(self.next_frame_time - time.time())
        return

    def close(self):
        input('Press Enter to end the simulation...')
        return

    def __validate_scenario_metadata(self):
        # Validate scenario environment parameters.
        assert self.scenario_metadata['environment'][
                   'num_channels'] > 0, 'Environment parameter \'num_channels\' is invalid.'
        assert self.scenario_metadata['environment']['max_steps'] > 0, 'Environment parameter \'max_steps\' is invalid.'
        assert self.scenario_metadata['environment']['observation_mode'] in self.metadata[
            'observation_modes'], 'Invalid observation mode. Must be one of the following options: {}'.format(
            self.metadata["observation_modes"])
        assert self.scenario_metadata['environment']['reward_mode'] in self.metadata[
            'reward_modes'], 'Invalid reward mode. Must be one of the following options: {}'.format(
            self.metadata["reward_modes"])
        if self.scenario_metadata['environment']['reward_mode'] == 'jam':
            assert self.scenario_metadata['environment']['target_entity'] in self.scenario_metadata[
                'entities'].keys() or self.scenario_metadata['environment'][
                       'target_entity'] == None,\
                'Invalid target entity name.\
                 Must correspond to the name of one of the entity labels in the scenario file.'
        # Validate scenario render parameters.
        assert self.scenario_metadata['render']['render_mode'] is None or self.scenario_metadata['render'][
            'render_mode'] in self.metadata[
                   'render_modes'], 'Invalid render mode. Must be one of the following options: {}'.format(
            self.metadata["render_modes"])
        assert self.scenario_metadata['render']['render_fps'] > 0, 'Render parameter \'render_fps\' is invalid.'
        assert self.scenario_metadata['render']['render_history'] > 0, 'Render parameter \'render_history\' is invalid.'

    def __observation_space_encoder(self, observation_vect):
        return np.vstack((self.info['spectrum_data'][0:self.samples_per_step].real,
                         self.info['spectrum_data'][0:self.samples_per_step].imag))

    def __get_entity_actions_and_observation(self):
        # Get each entities actions and determine the observation space.
        entity_idx = 0
        true_observation = np.zeros(self.num_channels, dtype=int)
        for entity in self.entity_list:
            entity_idx += 1
            entity_action = entity.get_action(self.info)
            self.info['action_history'][entity_idx][self.info['step_number']] = entity_action
            # If two or more entities' actions are to choose the same channel, set the observation to the number of entities + 1.
            if entity_action != -1:
                if true_observation[entity_action] == 0:
                    true_observation[entity_action] = entity_idx
                else:
                    true_observation[entity_action] = self.num_entities + 1

        # Set the observation for the player.
        if self.observation_mode == 'detect':
            player_observation = np.array(true_observation > 0, dtype=int)
        elif self.observation_mode == 'classify':
            player_observation = true_observation

        return true_observation, player_observation